import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "700"],
});

export const fontBangla = localFont({
  src: "./../fonts/mayaboti-normal.ttf",
  // weight:''
});

// {
// title: {
// default: "Hero Kidz",
// template: "%s | Hero Kidz",
// },
// description: "Generated by create next app",
// };

export const metadata = {
  metadataBase: new URL("https://hero-kidz-ten.vercel.app"),

  title: {
    default: "HeroKidz | Hero kidz products",
    template: "%s | HeroKidz",
  },

  description:
    "HeroKidz helps companies manage, assign, and track corporate assets efficiently.",

  applicationName: "HeroKidz",

  icons: {
    icon: "https://ibb.co.com/XxG77StM",
    apple: "https://ibb.co.com/XxG77StM",
  },

  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://hero-kidz-ten.vercel.app/",
    siteName: "HeroKidz",
    title: "HeroKidz | Smart Corporate Asset Management",
    description: "Track and manage company assets using HeroKidz.",
    images: [
      {
        url: "https://ibb.co.com/GQS2rcv8", // homepage preview
        width: 1200,
        height: 630,
        alt: "HeroKidz Homepage",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "HeroKidz | Hero Kidz Products",
    description: "Hero Kidz made simple.",
    images: ["https://ibb.co.com/GQS2rcv8"],
  },

  themeColor: "#2563eb",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={`${poppins.className}  antialiased`}>
          <header className="py-2 md:w-11/12 mx-auto">
            <Navbar />
          </header>
          <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-302px)]">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </NextAuthProvider>
  );
}
