import Products from "@/components/layouts/home/Products";
import React from "react";

export const metadata = {
  title: "ALL Products",
  description: "Generated by create next app",
};
const ProductsPage = () => {
  return (
    <div>
      <Products />
    </div>
  );
};

export default ProductsPage;
